export let users = [
  {
    phoneNo: '+923002245405',
    dob: '2023-11-22T13:04:53.734Z',
    niche: ['Gaming', 'Friendly fun videos'],
    willingToTravel: false,
    followers: 0,
    availability: '2023-11-15T00:00:00.000Z',
    showLocation: false,
    blockUsers: [],
    pushNotificationEnabled: false,
    role: 'USER',
    isDeleted: false,
    isVerified: true,
    otpInfo: {
      otp: '',
      expiresIn: 0,
    },
    isFirstTime: false,
    status: 'ACTIVE',
    firstName: 'Noman',
    lastName: 'Ali',
    email: 'noman@yopmail.com',
    location: {
      coordinates: [-95.36159136018071, 29.75419589694449],
      type: 'Point',
    },
    questionAndAnswers: [
      {
        question: 'Are you a full time content creator, or just for fun?',
        answer: 'Fulltime content creator',
      },
      {
        question: 'Select which applies?',
        answer: 'Video Creator',
      },
      {
        question: 'Do you understand, this is not a dating app?',
        answer: 'No',
      },
      {
        question: 'How often do you make content?',
        answer: '3-4 days/weekly',
      },
    ],
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    description: 'Passionate about creating amazing content',
    phoneNo: '+923331234567',
    email: 'alice.johnson@example.com',
    dob: '1992-08-21T00:00:00.000Z',
    location: {
      type: 'Point',
      coordinates: [-0.789012, 1.234567],
    },
    address: '456 Park Avenue, Citytown',
    niche: ['Van life', 'GYM', 'Gaming'],
    videos: [
      {
        url: 'https://www.example.com/video1.mp4',
        isProfileVideo: true,
      },
    ],
    willingToTravel: true,
    followers: 1200,
    socialMediaProfiles: {},
    availability: '2024-04-15T12:00:00.000Z',
    showLocation: true,
    questionAndAnswers: [
      {
        question: 'Are you a full-time content creator, or just for fun?',
        answer: 'Fulltime content creator',
      },
      {
        question: 'Select which applies?',
        answer: 'Photo Creator',
      },
      {
        question: 'Do you understand, this is not a dating app?',
        answer: 'Yes',
      },
      {
        question: 'How often do you make content?',
        answer: '5-6 days/weekly',
      },
    ],
    blockUsers: [],
    likedByMe: [],
    unLikedByMe: [],
    likedBySomeone: [],
    connections: [],
    pendingConnections: [],
    pushNotificationEnabled: true,
    role: 'USER',
    isDeleted: false,
    isVerified: true,
    isFirstTime: false,
    deviceToken: 'xyz789012345',
    profileVideo: 'https://www.example.com/profileVideo1.mp4',
    otpInfo: {
      otp: '',
      expiresIn: 0,
    },
    status: 'PENDING',
    gender: 'male',
  },
  {
    firstName: 'Bob',
    lastName: 'Smith',
    description: 'Adventure seeker and content enthusiast',
    phoneNo: '+923341234568',
    email: 'bob.smith@example.com',
    dob: '1988-05-10T00:00:00.000Z',
    location: {
      type: 'Point',
      coordinates: [-95.36396243286052, 29.75385126456334],
    },
    address: '789 Forest Lane, Villagetown',
    niche: ['Friendly fun videos', 'GYM'],
    videos: [
      {
        url: 'https://www.example.com/video2.mp4',
        isProfileVideo: false,
      },
    ],
    willingToTravel: true,
    followers: 900,
    socialMediaProfiles: {},
    availability: '2024-03-20T12:00:00.000Z',
    showLocation: false,
    questionAndAnswers: [
      {
        question: 'Are you a full-time content creator, or just for fun?',
        answer: 'Fulltime content creator',
      },
      {
        question: 'Select which applies?',
        answer: 'Video Creator',
      },
      {
        question: 'Do you understand, this is not a dating app?',
        answer: 'Yes',
      },
      {
        question: 'How often do you make content?',
        answer: '2-3 days/weekly',
      },
    ],
    blockUsers: [],
    likedByMe: [],
    unLikedByMe: [],
    likedBySomeone: [],
    connections: [],
    pendingConnections: [],
    pushNotificationEnabled: true,
    role: 'USER',
    isDeleted: false,
    isVerified: true,
    isFirstTime: false,
    deviceToken: 'abc123456789',
    profileVideo: 'https://www.example.com/profileVideo2.mp4',
    otpInfo: {
      otp: '',
      expiresIn: 0,
    },
    status: 'PENDING',
    gender: 'male',
  },
  {
    firstName: 'Charlie',
    lastName: 'Williams',
    description: 'Tech geek and content creator',
    phoneNo: '+923351232567',
    email: 'charlie.williams@example.com',
    dob: '1995-11-30T00:00:00.000Z',
    location: {
      type: 'Point',
      coordinates: [-2.345678, 3.456789],
    },
    address: '101 Tech Street, Technocity',
    niche: ['Gaming', 'Van life'],
    videos: [
      {
        url: 'https://www.example.com/video3.mp4',
        isProfileVideo: true,
      },
    ],
    willingToTravel: false,
    followers: 1500,
    socialMediaProfiles: {},
    availability: '2024-05-05T12:00:00.000Z',
    showLocation: true,
    questionAndAnswers: [
      {
        question: 'Are you a full-time content creator, or just for fun?',
        answer: 'Fulltime content creator',
      },
      {
        question: 'Select which applies?',
        answer: 'Tech Creator',
      },
      {
        question: 'Do you understand, this is not a dating app?',
        answer: 'Yes',
      },
      {
        question: 'How often do you make content?',
        answer: 'Daily',
      },
    ],
    blockUsers: [],
    likedByMe: [],
    unLikedByMe: [],
    likedBySomeone: [],
    connections: [],
    pendingConnections: [],
    pushNotificationEnabled: false,
    role: 'USER',
    isDeleted: false,
    isVerified: true,
    isFirstTime: false,
    deviceToken: 'pqr987654321',
    profileVideo: 'https://www.example.com/profileVideo3.mp4',
    otpInfo: {
      otp: '',
      expiresIn: 0,
    },
    status: 'PENDING',
    gender: 'male',
  },
  {
    firstName: 'David',
    lastName: 'Brown',
    description: 'Fitness enthusiast and wellness blogger',
    phoneNo: '+923561234567',
    email: 'david.brown@example.com',
    dob: '1985-04-12T00:00:00.000Z',
    location: {
      type: 'Point',
      coordinates: [4.56789, -5.678901],
    },
    address: '789 Fitness Road, Fitnesstown',
    niche: ['GYM', 'Friendly fun videos'],
    videos: [
      {
        url: 'https://www.example.com/video4.mp4',
        isProfileVideo: true,
      },
    ],
    willingToTravel: true,
    followers: 1800,
    socialMediaProfiles: {},
    availability: '2024-04-01T12:00:00.000Z',
    showLocation: false,
    questionAndAnswers: [
      {
        question: 'Are you a full-time content creator, or just for fun?',
        answer: 'Fulltime content creator',
      },
      {
        question: 'Select which applies?',
        answer: 'Fitness Creator',
      },
      {
        question: 'Do you understand, this is not a dating app?',
        answer: 'Yes',
      },
      {
        question: 'How often do you make content?',
        answer: '2-3 days/weekly',
      },
    ],
    blockUsers: [],
    likedByMe: [],
    unLikedByMe: [],
    likedBySomeone: [],
    connections: [],
    pendingConnections: [],
    pushNotificationEnabled: true,
    role: 'USER',
    isDeleted: false,
    isVerified: true,
    isFirstTime: false,
    deviceToken: 'lmn456789012',
    profileVideo: 'https://www.example.com/profileVideo4.mp4',
    otpInfo: {
      otp: '',
      expiresIn: 0,
    },
    status: 'PENDING',
    gender: 'male',
  },
  {
    firstName: 'Emma',
    lastName: 'Taylor',
    description: 'Lifestyle blogger and fashionista',
    phoneNo: '+923371634567',
    email: 'emma.taylor@example.com',
    dob: '1990-02-25T00:00:00.000Z',
    location: {
      type: 'Point',
      coordinates: [-3.456789, 2.345678],
    },
    address: '567 Style Street, Fashioncity',
    niche: ['Comedian', 'Friendly fun videos', 'Chef'],
    videos: [
      {
        url: 'https://www.example.com/video5.mp4',
        isProfileVideo: true,
      },
    ],
    willingToTravel: true,
    followers: 1600,
    socialMediaProfiles: {},
    availability: '2024-03-10T12:00:00.000Z',
    showLocation: true,
    questionAndAnswers: [
      {
        question: 'Are you a full-time content creator, or just for fun?',
        answer: 'Fulltime content creator',
      },
      {
        question: 'Select which applies?',
        answer: 'Lifestyle Creator',
      },
      {
        question: 'Do you understand, this is not a dating app?',
        answer: 'Yes',
      },
      {
        question: 'How often do you make content?',
        answer: '4-5 days/weekly',
      },
    ],
    blockUsers: [],
    likedByMe: [],
    unLikedByMe: [],
    likedBySomeone: [],
    connections: [],
    pendingConnections: [],
    pushNotificationEnabled: false,
    role: 'USER',
    isDeleted: false,
    isVerified: true,
    isFirstTime: false,
    deviceToken: 'stu789012345',
    profileVideo: 'https://www.example.com/profileVideo5.mp4',
    otpInfo: {
      otp: '',
      expiresIn: 0,
    },
    status: 'PENDING',
    gender: 'female',
  },
  {
    firstName: 'Frank',
    lastName: 'Miller',
    description: 'Foodie and cooking enthusiast',
    phoneNo: '+923382234567',
    email: 'frank.miller@example.com',
    dob: '1987-07-18T00:00:00.000Z',
    location: {
      type: 'Point',
      coordinates: [-1.234567, 3.456789],
    },
    address: '789 Cooking Lane, Foodtown',
    niche: ['ART', 'Sports'],
    videos: [
      {
        url: 'https://www.example.com/video6.mp4',
        isProfileVideo: false,
      },
    ],
    willingToTravel: false,
    followers: 1000,
    socialMediaProfiles: {},
    availability: '2024-05-20T12:00:00.000Z',
    showLocation: true,
    questionAndAnswers: [
      {
        question: 'Are you a full-time content creator, or just for fun?',
        answer: 'Fulltime content creator',
      },
      {
        question: 'Select which applies?',
        answer: 'Food Creator',
      },
      {
        question: 'Do you understand, this is not a dating app?',
        answer: 'Yes',
      },
      {
        question: 'How often do you make content?',
        answer: '2-3 days/weekly',
      },
    ],
    blockUsers: [],
    likedByMe: [],
    unLikedByMe: [],
    likedBySomeone: [],
    connections: [],
    pendingConnections: [],
    pushNotificationEnabled: true,
    role: 'USER',
    isDeleted: false,
    isVerified: true,
    isFirstTime: false,
    deviceToken: 'vwx456789012',
    profileVideo: 'https://www.example.com/profileVideo6.mp4',
    otpInfo: {
      otp: '',
      expiresIn: 0,
    },
    status: 'PENDING',
    gender: 'male',
  },
  {
    firstName: 'Near User 3',
    lastName: 'Near Lastname 3',
    description: 'Fitness and wellness enthusiast',
    phoneNo: '+1122384455',
    dob: '1988-08-08T00:00:00.000Z',
    location: {
      type: 'Point',
      coordinates: [-95.3615913601807, 29.75419589694451], // Slightly adjusted coordinates
    },
    niche: ['Couple collab'],
    videos: [
      {
        url: 'https://www.example.com/near_user3_video.mp4',
        isProfileVideo: true,
      },
    ],
    willingToTravel: true,
    followers: 1200,
    socialMediaProfiles: {},
    availability: '2024-03-20T12:00:00.000Z',
    showLocation: true,
    questionAndAnswers: [
      {
        question: 'Are you a full-time content creator, or just for fun?',
        answer: 'Fulltime content creator',
      },
      {
        question: 'Select which applies?',
        answer: 'Fitness Creator',
      },
      {
        question: 'Do you understand, this is not a dating app?',
        answer: 'Yes',
      },
      {
        question: 'How often do you make content?',
        answer: '2-3 days/weekly',
      },
    ],
  },
  {
    firstName: 'Near User 2',
    lastName: 'Near Lastname 2',
    description: 'Tech enthusiast and creator',
    phoneNo: '+98765432134',
    dob: '1995-05-05T00:00:00.000Z',
    location: {
      type: 'Point',
      coordinates: [-95.36159136018072, 29.75419589694448], // Slightly adjusted coordinates
    },
    niche: ['TikTok battle collab'],
    videos: [
      {
        url: 'https://www.example.com/near_user2_video.mp4',
        isProfileVideo: true,
      },
    ],
    willingToTravel: false,
    followers: 800,
    socialMediaProfiles: {},
    availability: '2024-05-01T12:00:00.000Z',
    showLocation: true,
    questionAndAnswers: [
      {
        question: 'Are you a full-time content creator, or just for fun?',
        answer: 'Fulltime content creator',
      },
      {
        question: 'Select which applies?',
        answer: 'Tech Creator',
      },
      {
        question: 'Do you understand, this is not a dating app?',
        answer: 'Yes',
      },
      {
        question: 'How often do you make content?',
        answer: 'Daily',
      },
    ],
  },
  {
    firstName: 'Near User 1',
    lastName: 'Near Lastname 1',
    description: 'Passionate content creator',
    phoneNo: '+123456189',
    dob: '1990-01-01T00:00:00.000Z',
    location: {
      type: 'Point',
      coordinates: [-95.3615913601807, 29.7541958969445], // Slightly adjusted coordinates
    },
    niche: ['Pet', 'Fishing'],
    videos: [
      {
        url: 'https://www.example.com/near_user1_video.mp4',
        isProfileVideo: true,
      },
    ],
    willingToTravel: true,
    followers: 500,
    socialMediaProfiles: {},
    availability: '2024-04-15T12:00:00.000Z',
    showLocation: true,
    questionAndAnswers: [
      {
        question: 'Are you a full-time content creator, or just for fun?',
        answer: 'Fulltime content creator',
      },
      {
        question: 'Select which applies?',
        answer: 'Video Creator',
      },
      {
        question: 'Do you understand, this is not a dating app?',
        answer: 'Yes',
      },
      {
        question: 'How often do you make content?',
        answer: '5-6 days/weekly',
      },
    ],
  },
];
